var $, config, gulp, paths, util;

gulp = require('gulp-help')(require('gulp'));

$ = require('gulp-load-plugins')();

config = require('../config');

paths = require('../paths');

util = require('../util');

gulp.task('script', false, function () {
  var key, results;
  results = [];
  for (key in config) {
    if (!config[key].script) {
      continue;
    }
    results.push(gulp.src(config[key].script).pipe($.plumber({
      errorHandler: util.onError
    })).pipe($.coffee()).pipe($.concat(key + '_script.js')).pipe($.uglify()).pipe($.size({
      title: 'Minified scripts'
    })).pipe(gulp.dest(paths["static"].min + "/script")));
  }
  return results;
});

gulp.task('script:dev', false, function () {
  var key, results;
  results = [];
  for (key in config) {
    if (!config[key].script) {
      continue;
    }
    results.push(gulp.src(config[key].script).pipe($.plumber({
      errorHandler: util.onError
    })).pipe($.sourcemaps.init()).pipe($.coffee()).pipe($.concat(key + '_script.js')).pipe($.sourcemaps.write()).pipe(gulp.dest(paths["static"].dev + "/script")));
  }
  return results;
});

// ---
// generated by coffee-script 1.9.2
